apiVersion: apps/v1
kind: Deployment
metadata:
  name: citizen-rest-app
  labels:
    app: citizen-service
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: citizen-service
  template:
    metadata:
      labels:
        app: citizen-service
    spec:
      containers:
      - name: citizen-container
        image: citizen-service:latest 
        imagePullPolicy: Never
        ports:
        - containerPort: 8089 # Ενημερωμένο στην πραγματική θύρα της εφαρμογής
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "2000m"
            memory: "1024Mi"
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        - name: DB_HOST
          value: "mysql-service"
        - name: DB_NAME
          value: "citizen_db"
        - name: SERVER_PORT
          value: "8089" # Ενημερωμένο για να συμφωνεί με τον Tomcat
