apiVersion: v1
kind: Service
metadata:
  name: citizen-service-lb
spec:
  # Τύπος LoadBalancer για πρόσβαση στην υπηρεσία
  type: LoadBalancer 
  selector:
    # Σύνδεση με τα Pods που έχουν το label app: citizen-service
    app: citizen-service 
  ports:
    - protocol: TCP
      port: 8089        # ΑΛΛΑΓΗ: Η θύρα στην οποία θα χτυπάς (IP:8089)
      targetPort: 8089  # Η θύρα της Java εφαρμογής μέσα στο container
