apiVersion: apps/v1
kind: Deployment
metadata:
  name: citizen-rest-app
  labels:
    app: citizen-service
spec:
  replicas: 1 # Μειωμένο σε 1 για εξοικονόμηση πόρων στο Minikube
  selector:
    matchLabels:
      app: citizen-service
  template:
    metadata:
      labels:
        app: citizen-service
    spec:
      containers:
      - name: citizen-container
        image: citizen-service:latest 
        imagePullPolicy: Never
        ports:
        - containerPort: 8089 
        resources:
          requests:
            cpu: "100m"   # Χαμηλή απαίτηση (0.1 CPU) για να ξεκινάει αμέσως
            memory: "256Mi"
          limits:
            cpu: "500m"   # Όριο μέχρι 0.5 CPU
            memory: "512Mi"
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        - name: DB_HOST
          value: "mysql-service"
        - name: DB_NAME
          value: "citizen_db"
        - name: SERVER_PORT
          value: "8089"

		  