apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  # Τα διαπιστευτήρια πρέπει να είναι κωδικοποιημένα σε base64
  # username: citizen_user
  username: Y2l0aXplbl91c2Vy
  # password: citizen_pass
  password: Y2l0aXplbl9wYXNz
