apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  # Ορίζουμε το πεδίο clusterIP σε None για headless υπηρεσία
  clusterIP: None 
  selector:
    # Επιλέγουμε την ενότητα mysql μέσω επιλογέα
    app: mysql 
  ports:
    - protocol: TCP
      port: 3306        # Η θύρα της υπηρεσίας
      targetPort: 3306  # Προώθηση στη θύρα 3306 του δοχείου
