apiVersion: v1
kind: Service
metadata:
  name: citizen-service-lb
  namespace: default   # Προσδιορισμός χώρου ονομάτων
  annotations:         # Στολισμοί για τον NLB
    # Καθορισμός τύπου Load Balancer σε NLB (Network Load Balancer)
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    # Καθορισμός διαχείρισης μέσω των IPs των δοχείων (pods)
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    # Καθορισμός ως εξωτερικός (internet-facing) για δημόσια πρόσβαση
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  type: LoadBalancer 
  selector:
    app: citizen-service 
  ports:
    - protocol: TCP
      port: 8089        
      targetPort: 8089

