apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: default      # ΠΡΟΣΘΗΚΗ (Γραμμή 5 βάσει οδηγίας)
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2   # ΠΡΟΣΘΗΚΗ (Γραμμή 10 βάσει οδηγίας)
  resources:
    requests:
      storage: 2Gi
  # Ο selector ΑΦΑΙΡΕΘΗΚΕ (όπως ζητάει η οδηγία)
